#### Creating Array 
#### np.array(): Create a NumPy array from a Python list or tuple.
#### np.zeros(): Create an array filled with zeros.
#### np.ones(): Create an array filled with ones.
#### np.empty(): Create an empty array.
#### np.arange(): Create an array with a range of values.
#### np.linspace(): Create an array with evenly spaced values.

In [4]:
## Creating array with .array()
import numpy as np
a = np.array([1,2,3,4,5])
b =np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)
print(a)
             

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[1 2 3 4 5]


In [14]:
## Creating with np.zeros
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [17]:
## Creating Array withnp.ones

a = np.ones((5,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [23]:
## Creating An Empty Array
## Create with 0 or some garbage value
a = np.empty((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [29]:
## Creating Array with arange
## Always Create 1D but you can reshape it latter

a = np.arange(1,6)
print(a)


[1 2 3 4 5]


In [28]:
import numpy as np

a = np.linspace(1, 10, 5)  # Create a one-dimensional array with 5 values from 1 to 10

print(a)

[ 1.    3.25  5.5   7.75 10.  ]



## Array Manipulation:
####	np.shape(): Get the shape (dimensions) of an array.
####	np.reshape(): Reshape an array.
####	np.transpose(): Transpose an array.
####	np.concatenate(): Join arrays along an axis.
####	np.split(): Split an array into smaller arrays.
####	np.vstack() and np.hstack(): Stack arrays vertically and horizontally.


In [34]:
arr = np.arange(1,11)
brr = arr.reshape(2,5)
print(arr)
print(brr)
arr.shape
brr.shape

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

In [36]:
## Transpose 
new = brr.transpose()
print(new)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [40]:
## concatenates arrays b and a together, resulting in a single arra

a= np.arange(1,5)
b= np.arange(6,10)
Result = np.concatenate((b,a))
print(Result)
print(a)
print(b)

[6 7 8 9 1 2 3 4]
[1 2 3 4]
[6 7 8 9]


In [41]:
##np.concatenate() combines arrays along an existing axis.
## np.stack() stacks arrays along a new axis, creating a higher-dimensional array.
Result = np.stack((a,b))
print(Result)

[[1 2 3 4]
 [6 7 8 9]]


In [47]:
Result = np.dstack((a,b)) ## H staxck for 3d array 
ustack =np.vstack((a,b))  ## Align Vertically Along with Rows
hsatck =np.hstack((a,b))  ## Along with Column 

print(Result ,"\n")
print(ustack ,"\n")
print(hsatck)


[[[1 6]
  [2 7]
  [3 8]
  [4 9]]] 

[[1 2 3 4]
 [6 7 8 9]] 

[1 2 3 4 6 7 8 9]


In [52]:
arr = np.array([1, 2, 3, 4, 5, 6])
result = np.split(arr, 3) ## it will devide into to sub array
for i in result:
    print (i)

print(result)

[1 2]
[3 4]
[5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]


## Mathematical Operations:

#### np.add(), np.subtract(), np.multiply(), np.divide(): Element-wise arithmetic operations.
#### np.dot(): Matrix multiplication.
#### np.sum(), np.mean(), np.median(), np.std(): Statistical operations.
#### np.min(), np.max(): Find minimum and maximum values.
#### np.exp(), np.log(), np.sqrt(): Exponential, logarithmic, and square root functions

In [68]:
a = np.arange(71,76)
b= np.arange(6,11)
# zerto =np.zeros((5,))

Result = np.add(a,b)
Result2 = np.subtract(b,a)
print(Result,'\n')
print(Result2,'\n')

[77 79 81 83 85] 

[-65 -65 -65 -65 -65] 



In [70]:
Result3 = np.multiply(a,b)
Result4 = np.divide(a,b)
print(Result3,'\n')
print(Result4)

[426 504 584 666 750] 

[11.83333333 10.28571429  9.125       8.22222222  7.5       ]


In [78]:
## In order to perform matrix multiplication, the number of columns in the first matrix 
## should be equal to the number of rows in the second matrix.
aa = np.array([[1, 2, 3], [4, 5, 6]])
bb = np.array([[8, 9], [10, 11], [12, 13]])

Result5 = np.dot(aa, bb)

print(Result5)

[[ 64  70]
 [154 169]]


In [83]:
## Mean Medium
## For Min Max Value

new = np.mean(a)
new2 = np.median(a)
new3 = np.min(a)
new4 = np.max(a)
new5 = np.sqrt(b)
print(new5)
print(new4)
print(new2)
print(new)
print(new3)

[2.44948974 2.64575131 2.82842712 3.         3.16227766]
75
73.0
73.0
71



## Random Number Generation:

#### np.random.rand(): Generate random numbers from a uniform distribution.
#### np.random.randn(): Generate random numbers from a standard normal distribution.
#### np.random.randint(): Generate random integers.
#### np.random.choice(): Randomly choose elements from an array.## 

In [87]:
import numpy as np

# Generate a 2x3 array of random numbers between 0 and 1
random_array = np.random.random((2, 3))

r =np.random.randint((2,9,4))  ## 4 random between 2 and 9
print(random_array)
print(r)

[[0.48303264 0.90845979 0.85938613]
 [0.03686083 0.75942649 0.62248591]]
[1 0 1]


In [91]:
a =np.random.rand(2,5)
b= np.random.randn(2,6)
print(b)

[[-0.49606589  0.03839101  0.64208292 -2.22529114  0.78190926 -1.69852003]
 [ 0.54594203  0.34087813  0.77895212 -0.11882999  1.56353362  0.73401284]]


The random.choice function in NumPy is used to randomly select elements from an array or a list. It takes the array or list as the first argument and the number of elements to be selected as the second argument

In [94]:
a=np.arange(1,9)
b = np.random.choice(a,size=4)
print(b)

[7 8 2 6]


File I/O:

np.save(): Save an array to a binary file.
np.load(): Load an array from a binary file.
np.savetxt(): Save an array to a text file.
np.loadtxt(): Load an array from a text file

### rray Aggregation:

### np.unique(): Find unique elements in an array.
### np.sort(): Sort elements in an array.
### np.argsort(): Get the indices that would sort an array.
### np.bincount(): Count occurrences of each value in an array of non-negative integers.